# Generated by Django 3.0.6 on 2020-05-11 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='품명')),
                ('price', models.IntegerField(verbose_name='가격')),
                ('size', models.IntegerField(choices=[(0, 'S'), (1, 'M'), (2, 'L'), (3, 'XL'), (4, 'XXL')])),
                ('category', models.IntegerField(choices=[(0, 'shoes'), (1, 'outer'), (2, 'pants'), (3, 'top'), (4, 'accesary')])),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_user.Shop')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1, verbose_name='수량')),
                ('order_data', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b_user.Product')),
            ],
        ),
    ]
