# Generated by Django 3.0.6 on 2020-05-12 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b_user', '0002_auto_20200512_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='subscribed_brand',
            field=models.ManyToManyField(blank=True, to='b_user.Shop'),
        ),
    ]
